---
- name: Is GoCD Agent already installed
  yum:
    list: go-agent
  register: is_installed

- name: GoCD Agent no installed
  block:
    - name: Update yum
      yum: 
        name: "*"
        state: latest

    - name: Install java-1.8.0-openjdk
      yum:
        name: java-1.8.0-openjdk
        state: present
    
    - name: Uninstall java-1.7.0-openjdk
      yum:
        name: java-1.7.0-openjdk
        state: absent

    - name: Install GoCD Agent
      yum:
        name: go-agent
        state: present
      become: yes

    - name: Start GoCD Agent
      shell: "/etc/init.d/go-agent start"
      become: yes

  when: is_installed.results|selectattr("yumstate", "match", "installed")|list|length == 0 
