---
- name: Is GoCD Agent already installed
  yum:
    list: go-agent
  register: is_installed

- name: GoCD Agent no installed
  block:
    - name: Update yum
      yum: 
        name: "*"
        state: latest
      become: yes

    - name: Install java-1.8.0-openjdk
      yum:
        name: java-1.8.0-openjdk
        state: present
    
    - name: Uninstall java-1.7.0-openjdk
      yum:
        name: java-1.7.0-openjdk
        state: absent

    - name: Get GoCD Repos
      get_url:
        url: https://download.gocd.org/gocd.repo
        dest: /etc/yum.repos.d/gocd.repo

    - name: Install GoCD Agent
      yum:
        name: go-agent
        state: present
      become: yes

    - name: GoCD Agent Configuration
      template:
        src: go-agent.j2
        dest: /etc/default/go-agent
        owner: go
        group: root
        mode: 0640

    - name: Start GoCD Agent
      shell: "/etc/init.d/go-agent start"
      become: yes
      become_user: go

  become: yes
  when: is_installed.results|selectattr("yumstate", "match", "installed")|list|length == 0 
