---
- name: Is GoCD already installed
  yum:
    list: go-server
  register: is_installed

- name: GoCD no installed
  block:
    - name: Update yum
      yum:
        name: *
        state: lastest

    - name: Install java-1.8.0-openjdk
      yum:
        name: java-1.8.0-openjdk
        state: present
    
    - name: Uninstall java-1.7.0-openjdk
      yum:
        name: java-1.7.0-openjdk
        state: absent

    - name: Install GoCD Server
      yum:
        name: go-server
        state: present

    - name: Start GoCD Server
      shell: "/etc/init.d/go-server start"
      become: yes
      become_user: root

  when: (is_installed.results|length == 1) or (is_installed.results[1].yumstate != 'installed') 