---
- name: Is GoCD Server already installed
  yum:
    list: go-server
  register: is_installed

- name: GoCD Server no installed
  block:
    - name: Update yum
      yum: 
        name: "*"
        state: latest

    - name: Install java-1.8.0-openjdk
      yum:
        name: java-1.8.0-openjdk
        state: present
    
    - name: Uninstall java-1.7.0-openjdk
      yum:
        name: java-1.7.0-openjdk
        state: absent

    - name: Get GoCD Repos
      get_url:
        url: https://download.gocd.org/gocd.repo
        dest: /etc/yum.repos.d/gocd.repo

    - name: Install GoCD Server
      yum:
        name: go-server
        state: present

    - name: Start GoCD Server
      shell: "/etc/init.d/go-server start"
      become: yes
      become_user: go

  become: yes
  when: is_installed.results|selectattr("yumstate", "match", "installed")|list|length == 0 
